[tool.ruff]
line-length = 120
target-version = "py311"
select = ["E", "F", "I", "UP"]
ignore = ["D203"]
show-source = true

[tool.ruff.lint.isort]
known-first-party = ["fastapi_app"]

[tool.black]
line-length = 120
target-version = ["py311"]
